# Generated by Django 3.2.6 on 2021-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
